veracrypt_path: C:\Program Files\VeraCrypt

bitwarden:
  url: http://localhost:5000
  password_base64: a2FtdXJp
  credential_name: volume_password

volume:
  folder: ./test
  name: test
  mount_point: Z:\
  size: 10M
  filesystem: ExFAT

default_structure:
  - name: common
    children:
      - name: images
      - name: documents
        children:
          - name: pdf
          - name: word
          - name: excel
          - name: powerpoint
          - name: others
      - name: videos
      - name: music
      - name: projects
      - name: others
  - name: test
    children:
      - name: test1
      - name: test2
      - name: test3
      - name: test4
      - name: test5
